### ISSUE TITLE
Vinyl - Record compatibility

### ISSUE THREAD

**Issue by yoshuawuyts** [node-task/spec#19]
I'm wondering if [record](https://github.com/node-task/record) could become compliant with the [vinyl spec](https://github.com/wearefractal/vinyl) in order to natively consume gulp plugins. A discussion regarding gulp / node-task compatibility has been going over at [gulp issue 86](https://github.com/gulpjs/gulp/issues/86#issuecomment-31592414). 
## Links
- [Gulp / node-task compatibility discussion](https://github.com/gulpjs/gulp/issues/86#issuecomment-31592414)
- [Vinyl virtual file format](https://github.com/wearefractal/vinyl)
- [Vinyl-fs file system adapter](https://github.com/wearefractal/vinyl-fs)

**Comment by yocontra** [comment]
The two are pretty similar - you could convert pretty easily or make a shim.

**Comment by tkellen** [comment]
Yes!

ref: wearefractal/vinyl#10
