### ISSUE TITLE
Infer basic info from package.json

### ISSUE THREAD

**Issue by domenic** [node-task/spec#2]
name, description, and version seem like no-brainers. Thoughts?

**Comment by tkellen** [comment]
There will be many situations where a task might not exist as an NPM module (inline in Gruntfiles for short tasks, as a part of an internal project where you're requiring the task directly, etc).  That said, there is nothing preventing you from doing this in your own modules.

**Comment by domenic** [comment]
OK. Maybe a helper? `Task.createFromPackage` or similar.

**Comment by tkellen** [comment]
The arguments sent to Task.create() are merged before the constructor is called, so you could do something like:

``` js
Task.create({
...
}, require('package.json'));
```

**Comment by tkellen** [comment]
Just so you know, I'm not against this idea at all, but it would be nice to solve it without an additional API.

**Comment by domenic** [comment]
I think the argument-merging is fine, as long as there's a good match between the `package.json` property names and the task ones. I'd suggest featuring it prominently in the documentation though, since it sounds like you're against adding an easily-discoverable API.
