### ISSUE TITLE
make *almost everything* optional

### ISSUE THREAD

**Issue by millermedeiros** [node-task/spec#9]
for me it seems _unnecessary_ to ask for that many properties. I would like the runner to work even with the user doesn't provide `name`, `version`, `options`, `description`, `on`, `off`... only thing that I think that should be required is the method `run`.

**Comment by tkellen** [comment]
I can agree with that.  I've made almost everything optional, but I'm still requiring the inclusion of on/off/emit in the spec for now.  That _might_ go optional too, but I want to talk with a few more people about it first.

**Comment by tkellen** [comment]
We're going to stick with making tasks inherit EventEmitter functionality for consistency.  At the moment, the only required properties for a basic task to work with a runner are on/off/emit/run.  I hope that's a good enough compromise.
